ParseXS: give error on unmatched length(foo)
In this form of XSUB:

    foo(char *s, int length(s))

if the length pseudo-parameter's name didn't match another parameter,
e.g.

    foo(int length(s))

then it would quietly generate bad C code. This commit makes it produce
an error instead:

    Error: length() on non-parameter 's'

It does this by adding a new field, 'has_length' on Param objects,
which is set by a quick scan of all params just after the XSUB's
signature has been parsed.

This also removes one more "runtime" usage of the $pxs->{xsub_params}
value in an as_code() method.